"""add status column and nullable fields

Revision ID: 2580e15f4957
Revises: 7c12bd6edd18
Create Date: 2026-05-26 18:46:09.198278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2580e15f4957'
down_revision: Union[str, Sequence[str], None] = '7c12bd6edd18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('status', sa.String(), nullable=True))
    op.alter_column('meetings', 'transcript',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meetings', 'transcript',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('meetings', 'status')
    # ### end Alembic commands ###
